# SPDX-FileCopyrightText: Copyright (c) 2017-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
readers:
  - "urn:github:526301"
docker:
  image: yegor256/rultor-image:1.21.0
assets:
  settings.xml: yegor256/cqfn-secrets#jpeek-settings.xml
  settings-heroku.xml: yegor256/cqfn-secrets#jpeek-settings-heroku.xml
  pubring.gpg: yegor256/cqfn-secrets#pubring.gpg
  secring.gpg: yegor256/cqfn-secrets#secring.gpg
  id_rsa: yegor256/cqfn-secrets#dokku-id_rsa
  id_rsa.pub: yegor256/cqfn-secrets#dokku-id_rsa.pub
install: |
  pdd -f /dev/null
merge:
  script: |
    mvn clean install -Pqulice --errors --settings ../settings.xml
    mvn clean site -Psite --errors --settings ../settings.xml
release:
  sensitive:
    - id_rsa
    - id_rsa.pub
    - settings.xml
    - settings-heroku.xml
  script: |-
    export GPG_TTY=$(tty)
    gpg --import /home/r/pubring.gpg
    gpg --allow-secret-key-import --no-tty --batch --import /home/r/secring.gpg
    [[ "${tag}" =~ ^[0-9]+(\.[0-9]+)*$ ]] || exit -1
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -Pjpeek -Psonar -Pqulice -Psonatype --errors --settings ../settings.xml
    cp ../settings-heroku.xml settings.xml
    mvn clean package -Pqulice --errors --batch-mode
    rm -rf ~/.ssh
    mkdir ~/.ssh
    mv ../id_rsa ../id_rsa.pub ~/.ssh
    chmod 600 ~/.ssh/*
    echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" > ~/.ssh/config
    git remote add dokku dokku@dokku.jpeek.org:jpeek
    git add settings.xml
    git commit -m 'settings.xml' && git push -f dokku $(git symbolic-ref --short HEAD):master
    git reset HEAD~1
    rm settings.xml
    curl -f --connect-timeout 15 --retry 5 --insecure --retry-delay 30 https://i.jpeek.org > /dev/null
