/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2017 Yegor Bugayenko
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.jpeek.asm.func;

import org.cactoos.Scalar;
import org.cactoos.scalar.Ternary;
import org.objectweb.asm.FieldVisitor;
import org.objectweb.asm.Opcodes;

/**
 * Function that will be called on visiting class field
 * that wasn't generated by compiler.
 *
 * <p>After compilation byte code may contain more fields than you declared
 * in source code. For example all inner classes contain field {@code this$0},
 * it's a reference to outer class. You don't declare this one field
 * explicitly, but compiler will generate it implicitly. Use this one function
 * to filter all fields and to react only on explicitly declared fields in
 * the source code.</p>
 *
 * @author Sergey Karazhenets (sergeykarazhenets@gmail.com)
 * @version $Id$
 * @since 0.13
 */
public final class OnNotGenField implements
    Func5<Integer, String, String, String, Object, Scalar<FieldVisitor>> {

    /**
     * Function that will be called when class visitor will visit
     * class field wasn't generated by compiler.
     */
    private final Func5<Integer, String, String, String, Object,
        Scalar<FieldVisitor>> func;

    /**
     * Ctor.
     * @param func Function to call on field visit event
     *  for field wasn't generated by compiler.
     */
    public OnNotGenField(
        final Func5<Integer, String, String, String, Object,
            Scalar<FieldVisitor>> func
    ) {
        this.func = func;
    }

    @Override
    // @checkstyle ParameterNumberCheck (1 line)
    public Scalar<FieldVisitor> apply(final Integer access, final String name,
        final String desc, final String signature, final Object value
    ) throws Exception {
        return new Ternary<Scalar<FieldVisitor>>(
            () -> !name.contains("$"),
            () -> this.func.apply(access, name, desc, signature, value),
            () -> () -> new FieldVisitor(Opcodes.ASM6) { }
        ).value();
    }
}
