# SPDX-FileCopyrightText: Copyright (c) 2017-2026 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: shellcheck
'on':
  push:
    branches:
      - master
    paths:
      - '**.sh'
      - '**.bash'
      - '.github/workflows/shellcheck.yml'
  pull_request:
    branches:
      - master
    paths:
      - '**.sh'
      - '**.bash'
      - '.github/workflows/shellcheck.yml'
jobs:
  shellcheck:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
